dataset:
  data_path: data/indextrack/indextrack5.txt
  loader_name: indextrack_loader
  name: indextrack5
exp_dir: exp/Random
model:
  count: 10
  model_config: volatility
  name: Random
  port_mean: 20
  port_std: 3
  weight_method: MVO_weight
runner: RandomRunner
test:
  end_date: 290
  start_date: 201
  test_method: future_performance
train:
  end_date: 200
  start_date: 0
