dataset:
  data_path: data/indextrack/indextrack2.txt
  loader_name: indextrack_loader
  name: indextrack2
exp_dir: exp/Random
model:
  count: 10
  model_config: return
  name: Random
  port_mean: 10
  port_std: 2
  weight_method: MVO_weight
runner: RandomRunner
test:
  end_date: 290
  start_date: 201
  test_method: future_performance
train:
  end_date: 200
  start_date: 0
