dataset:
  data_path: data/indextrack/indextrack1.txt
  loader_name: indextrack_loader
  name: indextrack1
exp_dir: exp/Random
model:
  count: 10
  model_config: return
  name: Random
  port_mean: 5
  port_std: 1
  weight_method: uniform_weight_returns
runner: RandomRunner
test:
  end_date: 290
  start_date: 201
  test_method: future_performance
train:
  end_date: 200
  start_date: 0
