dataset:
  data_path: data/indextrack/indextrack3.txt
  loader_name: indextrack_loader
  name: indextrack3
exp_dir: exp/Mantegna
model:
  name: Mantegna
  weight_method: HRP_weight
runner: MantegnaRunner
test: {}
train:
  end_date: 200
  start_date: 0
