dataset:
  data_path: data/indextrack/indextrack5.txt
  loader_name: indextrack_loader
  name: indextrack5
exp_dir: exp/Mantegna
model:
  model_config: return
  name: Mantegna
  weight_method: uniform_weight_returns
runner: MantegnaRunner
test: {}
train:
  end_date: 200
  start_date: 0
