test:
    test_method: future_performance
    start_date: 201
    end_date: 290
    train_results: exp/Mantegna/Mantegna_sp500_2021-Sep-21-13-38-58/mantegna_results.csv

    test_method: noise_stability
    sort_column: sharpe
    noise_sigma: 0.01
    start_date: 201
    end_date: 290

    test_method: time_stability
    sort_column: sharpe
    test1:
      start_date: 0
      end_date: 20
    test2:
      start_date: 20
      end_date: 40