---
  runner: RPSRunner
  test: False
  dataset:
    name: 'indextrack1'
    loader: IndexTrackingLoader
    data_path: data/
  model:
    name: 'RPS'
    dimensions: 64
    walk_length: 2
    num_walks: 50
    workers: 7
    weight_function: HRP
    cluster_method: fuzzy_c_means
    sort_measure: sharpe