---
  runner: RPSRunner
  test: False
  dataset:
    name: 'sp500'
    loader: SP500_loader
    data_path: 'data/SP500/SP_20130208_20180207.csv'
  model:
    name: 'RPS'
    dimensions: 64
    walk_length: 2
    num_walks: 50
    workers: 7
    weight_function: HRP
    cluster_method: fuzzy_c_means
    sort_measure: sharpe
    distance_graph_function: 'coth'