dataset:
  data_path: data/indextrack/indextrack1.txt
  loader_name: indextrack_loader
  name: indextrack1
exp_dir: exp/RPS
model:
  batch_words: 4
  cluster_method: fuzzy_c_means
  clustering_method: FCM_clustering
  dimensions: 64
  distance_transformer: coth_transformer
  max_memberships: 2
  min_count: 1
  model_config: null
  n_clusters: 8
  name: RPS
  num_walks: 50
  sort_measure: sharpe
  walk_length: 2
  weight_method: HRP_weight
  window: 10
  workers: 7
runner: RPSRunner
test: null
train:
  end_date: 200
  start_date: 0
