---
  runner: SplexRunner
  exp_dir: exp/Splex
  dataset:
    name: indextrack1
    loader_name: indextrack_loader
    data_path: data/indextrack/indextrack1.txt
  model:
    name: Splex
    weight_method: HRP_weight
    weight_limit: 0.2
    s: 2
  train:
    start_date: 0
    end_date: 200
  test: